services:
  l5_proxy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=homelab
    networks:
      - homelab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/nas/homelab/caddy/l5_proxy/data:/data
    restart: unless-stopped
  l4_proxy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    restart: unless-stopped

networks:
  homelab:
    external: true
