services:
  plex:
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    volumes:
      - /mnt/nas/homelab/plex/plex/config:/config
      - /mnt/nas/homelab/plex/plex/data:/data
      - /mnt/nas/homelab/plex/plex/transcode:/transcode
    labels:
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=plex.png
      - homepage.href=https://media.pitlor.dev/
      - homepage.description=Media server (like Netflix)
      - caddy=media.pitlor.dev
      - caddy.reverse_proxy={{upstreams 32400}}
    networks:
      - homelab

networks:
  homelab:
    external: true
