version: '3''

services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - /mnt/homelab/vaultwarden:/data
    labels:
      - homepage.group=Media
      - homepage.name=Vaultwarden
      - homepage.icon=vaultwarden.png
      - homepage.href=https://passwords.pitlor.dev/
      - homepage.description=Password Manager
      - caddy=passwords.pitlor.dev
      - caddy.reverse_proxy={{upstreams 80}}
    networks:
      - homelab

networks:
  homelab:
    external: true
