version: '3'

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - /path/to/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock # pass local proxy
    restart: unless-stopped
    labels:
      - caddy=homepage.pitlor.local
      - caddy.reverse_proxy={{upstreams}}

networks:
  homelab:
    external: true
