services:
  portainer:
    image: portainer/portainer-ee:latest
    restart: unless-stopped
    volumes:
      - /mnt/nas/homelab/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - homepage.group=Infrastructure
      - homepage.name=Portainer
      - homepage.icon=portainer.png
      - homepage.href=https://containers.pitlor.local/
      - homepage.description=Manage Docker containers
      - caddy=containers.pitlor.local
      - caddy.reverse_proxy={{upstreams 9443}}
    networks:
      - homelab

networks:
  homelab:
    external: true
