version: '3'

services:
  portainer:
    image: portainer/portainer-ee:latest
    restart: unless-stopped
    volumes:
      - /mnt/homelab/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8000:8000'
      - '9443:9443'
    labels:
      - homepage.group=Infrastructure
      - homepage.name=Portainer
      - homepage.icon=portainer.png
      - homepage.href=https://containers.pitlor.local/
      - homepage.description=Manage Docker containers
      - caddy=containers.pitlor.local
      - caddy.reverse_proxy={{upstreams}}

networks:
  homelab:
    external: true
