services:
  minecraft:
    image: itzg/minecraft-server:latest
    restart: unless-stopped
    volumes:
      - /mnt/nas/homelab/minecraft/minecraft/data:/data
    labels:
      - TODO does caddy to udp forwarding?
    networks:
      - homelab

networks:
  homelab:
    external: true
