version: '3'

services:
  tandoor_db:
    restart: unless-stopped
    image: postgres:15-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env

  tandoor_web:
    restart: unless-stopped
    image: vabene1111/recipes:latest
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes

  tandoor_nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - 8083:80
    env_file:
      - ./.env
    depends_on:
      - web_recipes
    volumes:
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
      - ./mediafiles:/media:ro
    labels:
      - homepage.group=Media
      - homepage.name=Tandoor
      - homepage.icon=tandoor.png
      - homepage.href=https://recipes.pitlor.dev/
      - homepage.description=Recipe Database
      - caddy=recipes.pitlor.dev
      - caddy.reverse_proxy={{upstreams}}

networks:
  homelab:
    external: true
